### ISSUE TITLE
DELETE Request?

### ISSUE THREAD

**Issue by kikemarto** [mbarwick83/instagram#1]
Hi,

You can make requests deletion? From what I have read in the library I can not find it.

I can collaborate creating it.

Greetings.

Google translator.

**Comment by mbarwick83** [comment]
This library doesn't handle the endpoints. You have to specify them using the POST and GET examples in the README. If a "delete" [API endpoint](https://www.instagram.com/developer/endpoints/) doesn't exist, which appears there isn't, nothing we can do.

**Comment by mbarwick83** [comment]
Good catch. I don't ahem time to do it right now, but shouldn't be a big change/edit. Give me some time - otherwise, feel free to submit a PR and I'll commit it.

**Comment by mbarwick83** [comment]
I'm not seeing any docs about deleting posts/content via Instagram API...a quick Google looks like this isn't possible. Docs have very little documentation on the matter.

**Comment by kikemarto** [comment]
Delete likes and comments, post can not.

**Comment by kikemarto** [comment]
#2 Waiting for review, thanks. :)

**Comment by mbarwick83** [comment]
Note, I also just made another change to the file, PSOT requests section. The optional authorization boolean should have been the last option in method. If you're currently using the POST method, make sure the true (or false) in the method call is the third option versus second - or don't include it at all. i.e. `$this->instagram->post('v1/media/{media-id}/comments', ['text' => 'this is a comment', 'access_token' => $oauth->access_token], false)`

**Comment by kikemarto** [comment]
Cool, modified, thanks.
