### ISSUE TITLE
Problem Timeout

### ISSUE THREAD

**Issue by kikemarto** [mbarwick83/instagram#3]
Hi,

Can we work time with a variable instead of a constant to avoid this error?

![image](https://cloud.githubusercontent.com/assets/14853156/20910907/d1f8fe8a-bb3a-11e6-960b-8c69dd72569c.png)

Greetings.

**Comment by mbarwick83** [comment]
Sure, what do you have in mind? I could also up the time out amount, to say 5. Anything past that (even 2) is probably problematic code.

**Comment by kikemarto** [comment]
I'm from Venezuela, and the internet sucks. Hahaha

It was just to develop.

Thanks.

**Comment by mbarwick83** [comment]
Note, I increased the timeout time to 8.0. 2 seconds before, was a little short. Too limited.
