### ISSUE TITLE
OAuth Access Token

### ISSUE THREAD

**Issue by claytongf** [mbarwick83/instagram#4]
Hi
I'm trying to get an access token to get recent media from tags.
But, when I use get or post requests to get a response code or access token, it receives null

public function getCode(){
        $code = $this->instagram->get('oauth/authorize', ['client_id' => config('instagram.client_id'), 'redirect_uri' => config('instagram.redirect_uri'), 'response_type' => 'code', 'scope' => config('instagram.scopes')]);

return $code;
    }
In this case, $code is null
How can I get the authorization code correctly?

Thanks

**Comment by mbarwick83** [comment]
Did you look at the example usage on the README for getting the user's access token? Please follow the instructions on there exactly. You're also specifying config variables, but those are already added, assuming you've set-up the package correctly (again, as per README).

**Comment by claytongf** [comment]
Hi,
Yes. But, my question is: the getLoginUrl method receive only the full url. Should I use as post command?
And the callback method in the example shows $request->code. But where should I get this code information?

**Comment by mbarwick83** [comment]
`getLoginUrl` is the URL for the user to authorize (i.e. go through the oAuth step). The callback method is the redirect_uri you set up in the Instagram config file. Set up a `get` route for that and return `$request->all()` and you'll see the returned object, with the `code` returned from Instagram. Use this code to get the access token, as per example.

**Comment by claytongf** [comment]
In this case, I used this code to get the code value
`$code = $instagram->get('oauth/authorize', ['client_id' => config('instagram.client_id'), 'redirect_uri' => config('instagram.redirect_uri'), 'response_type' => 'code', 'scope' => config('instagram.scopes')]);`
But it returns null. Is there anything that I forgot to setup before?

**Comment by mbarwick83** [comment]
That won't work. This is an oAuth related package. A user needs to authorize your app/service. There's no way around it. If you want to make requests on behalf of a user, they have the physically authorize your app to do so (i.e. via the `getLoginUrl` link).

**Comment by claytongf** [comment]
I got it. Do you have a recommendation of an oauth package that can work with yours?
Or, if you want, I can suggest to implement that feature into your package. It should be great use an oauth and get/post requests to get media.

**Comment by mbarwick83** [comment]
**This IS AN OAUTH package.** I don't think you're understanding the flow and authorization steps needed. The code you're trying to get to work will never work - with any package, including mine.

If you're trying to get a specific user's media, on their behalf, they (the user) needs to authorize your application to do so. They MUST follow the `getLoginUrl` link, sign in (if they're not already), authorize the scopes/permissions you want to perform on behalf of the user, and then Instagram directs the user back to the redirect url you specified, where you handle the callback (i.e. getting the actual access token).

What are you trying to achieve exactly? Get Instagram posts/media from users on your site? 

If so, you must follow the example for this package. The example on the README, `getLoginUrl` and the callback example do everything that's needed on this [page](https://www.instagram.com/developer/authentication/). So there's no need to do it yourself.

**Comment by claytongf** [comment]
I think I got the idea.
Before the Instagram changes their policy, it was easy to do that.
My idea is to get posts/media in my site. But each user has different configurations when login into my site. So, with the package, I start getting the url from getLoginUrl, and then, the user authorizes and redirects to the redirect_uri that I provided. In this idea that each user has different set ups, I'm figuring out how to use it, getting the user's config after redirecting by the uri

**Comment by mbarwick83** [comment]
Why make the `scopes` user defined!? Just set this across the board. It's a nightmare otherwise. It's pretty basic scopes and permissions anyways. Shouldn't need to change per user at all. No point. Instagram is mostly "read only" api anyways. You can't post images/posts, etc. POST methods are used to add/delete comments, to like, etc. Once you get the user's access token, you can use whatever endpoint you like.
